### ISSUE TITLE
Insta360 accel unit wrong

### ISSUE THREAD

**Issue by tly000** [AdrianEddy/telemetry-parser#17]
I think the unit for the accelerometer data of Insta360 files seems to be wrong. 

```
if self.is_raw_gyro {
    let accl_scale = 32768.0 / self.acc_range.unwrap_or(16.0); // ± 16g
    ...
}

...
insert_tag(&mut map, tag!(parsed Accelerometer, Unit, "Accelerometer unit", String, |v| v.to_string(), "m/s²".into(),  Vec::new()));
```

Does this mean that the accel uni in normalized_imu is always g?

Thanks!

**Comment by AdrianEddy** [comment]
Indeed it was wrong. 
Fixed in latest commit. `normalized_imu` now always returns deg/s for gyro and m/s^2 for accelerometer
