### ISSUE TITLE
Windows version of the app does not open

### ISSUE THREAD

**Issue by Slint7** [AdrianEddy/telemetry-parser#22]
Good day

I have Windows 10. I tried the v0.2.7, 32 & 64 versions and tried running it as administrator.

When I double-click the .exe file, nothing happens.

Do you have an explanation on how to use the telemetry-parser?

Am I using it incorrectly, do I need a prerequisite or can Windows security be blocking the app?

Thanks for the great work.

**Comment by Slint7** [comment]
Thank you for the explanation.

**Comment by Slint7** [comment]
When I drag Gopro footage to the .exe it works fine however, I can't get
the Open Camera Sensors .csv files working.

How does it work with the Andoid app, Open Camera Sensors?

(The Open Camera Sensor files are 4 different .csv files for the
gyro, accelerometer, timestamps and magnetic info)

I want to use the Open Camera Sensor data with Gyroflow video stabilization.

**Comment by AdrianEddy** [comment]
You don't have to use this app at all then, just open the files directly in Gyroflow v1.4.0

**Comment by Slint7** [comment]
Thank you.
