### ISSUE TITLE
Failed to identify as OpenCamera Sensor format since the data in scientific notation

### ISSUE THREAD

**Issue by 634454423** [AdrianEddy/telemetry-parser#28]
hello, i record a video in OpenCamera Sensor APP in my phone , and it produces a gyro data in csv file. but this project failed to identify the correct format because some of the number recorded in scientific notation( it has 'E', just like this:) . 
![image](https://github.com/AdrianEddy/telemetry-parser/assets/51955380/a0c14304-5d18-43e7-adae-2847f2b6919d)

Then i just try to make the data show as actual text , and it success to identify the csv file. Hope for further improving so i don't need modify the csv file manually.

**Comment by AdrianEddy** [comment]
Should be fixed in Gyroflow v1.5.4 (https://github.com/gyroflow/gyroflow/releases/tag/v1.5.4)
