### ISSUE TITLE
How to make sense of data (from wasm)?

### ISSUE THREAD

**Issue by HDv2b** [AdrianEddy/telemetry-parser#30]
Hi,

I'm testing the WASM script for a Go Pro 10 video. I'm having a lot of success, but would like to understand how to read this data:
![image](https://github.com/AdrianEddy/telemetry-parser/assets/1381698/c33ce876-42e5-4f46-a73c-46707a39f847)

With the 10 GPS points given, how to they relate to each other? Do I assume they're equidistant by x milliseconds apart, and if so, what is x?

Thanks

**Comment by AdrianEddy** [comment]
Refer to GPMF format description: https://github.com/gopro/gpmf-parser#hero5-black-with-gps-enabled-adds to learn about the GPS format. 
These 5 values are (latitude, longitude, altitude (WGS 84), 2D ground speed, and 3D speed)

There are 10 samples in a "packet". In GPMF, samples are grouped together in these packets, but they don't really mean anything and you can just collect all samples to a single array independently. 

Each packet has a timestamp, so you have to calculate timestamp per sample by either calculating an average timestamp diff using first and last sample in the entire file, or track previous packet timestamp and divide that by the number of samples in the packet
