### ISSUE TITLE
Metadata with negative timestamps and gyroscopic scale meanings?

### ISSUE THREAD

**Issue by cuixing158** [AdrianEddy/telemetry-parser#33]
Part of the gyroscope metadata I got is as follows:
```text
gyrodata:
'Data':[{'t': -2.316133000000054, 'x': 170.6205538726403, 'y': -94.22785488252927, 'z': -367.63533285095224}, {'t': -2.3151330000000536, 'x': 182.6236995561125, 'y': -112.0764583655591, 'z': -410.69751866875436}, {'t': -2.3141330000000537, 'x': 195.61980039067564, 'y': -128.9180670895991, 'z': -453.7609785702092},...]
'Unit':'deg/s'
'Scale':16.384
'Orientation':'Xyz'
```
What does  mean by the output above having a negative value for `t`, is it invalid, and is it correct if it is followed by a positive one? Also what is the meaning of 'Scale', is it dividing 'x', 'y', 'z' of 'Data' by 'Scale' to get the real angular velocity data (deg/s)? thanks in advance!

**Comment by AdrianEddy** [comment]
It depends on the camera, but generally it means that the gyro data is sampled before the first video frame.

All cameras have different timing though, so to get accurate per-video-frame data, you'll need some additional calculations depending on the camera, look for `per_frame_time_offsets` in gyroflow's source code

the number in `Data` divided by `Scale` will result in `Unit`. If you're using `normalized_imu` functions then this is already calculated for you
