### ISSUE TITLE
additional_data while parsing .insv

### ISSUE THREAD

**Issue by artemkurylev** [AdrianEddy/telemetry-parser#35]
Hi, thank you for the great tool! May I ask you question about camera (insta360) intrinsic parameters defined in offset section in adiitional_data -  how are they defined, and what's the difference between offset, offset_v2 , offset_v3, and original offsets

**Comment by AdrianEddy** [comment]
The definition is [here](https://github.com/AdrianEddy/telemetry-parser/blob/master/src/insta360/mod.rs#L233) and the lens model is implemented [here](https://github.com/gyroflow/gyroflow/blob/master/src/core/stabilization/distortion_models/insta360.rs)

As for the differences - I have no idea, I'm only using the offset_v3 and that seems to work fine
