### ISSUE TITLE
No support for InstaX3 and X4

### ISSUE THREAD

**Issue by DuVogel87** [AdrianEddy/telemetry-parser#37]
Any plans for supporting the x3 and x4 in near time? 

Thanks!

**Comment by AdrianEddy** [comment]
do you have a sample file?

**Comment by DuVogel87** [comment]
sorry for my late answer. I just recorded some seconds so that you have the native file format from my instax3. 
here is the data for you to download: 
https://we.tl/t-G6xLapz7LA

can you provide a general idea if you are able to support the x3 or x4 in the near future? it would be very helpful. 
thanks.

**Comment by AdrianEddy** [comment]
it already parses that file correctly

**Comment by DuVogel87** [comment]
Ah okay. It doesnt appear under supported formats. But good to know that. I will try it now.
