### ISSUE TITLE
Clarification on Supported Formats and Metadata Handling

### ISSUE THREAD

**Issue by DuVogel87** [AdrianEddy/telemetry-parser#38]
I have a couple of questions regarding the --dump and --imuo options in the gyro2bb.exe tool:

    Does it matter which encoding format I choose for the input file? Specifically, I am considering the following formats:
        H.264
        H.265 (HEVC)
        ProRes 422 LT
        ProRes 422

    Is it possible to work with the native .insv file format from Insta360, or does the tool only support MP4 files for processing?

I would appreciate any insights on these points.

Thank you for your help!

**Comment by AdrianEddy** [comment]
the format doesn't matter, all of these are supported
yes, insv are regular mp4 files, they just have a different extension. It doesn't matter for telemetry-parser
