### ISSUE TITLE
Question Regarding Output Location

### ISSUE THREAD

**Issue by DuVogel87** [AdrianEddy/telemetry-parser#39]
I have a question regarding the output location when using the --dump and --imuo xZy commands. In the --help documentation, I couldn't find any information about where the results are saved.

Could you please clarify where the output is stored when I run these commands?

Thank you for your help!

**Comment by AdrianEddy** [comment]
it is only printed to the terminal. To save it to file, use standard command line redirection, like `gyro2bb --dump file.mp4 > metadata.txt`

alternatively you can export the metadata to json in Gyroflow using `Motion Data -> Export` (or use the gyroflow cli to do that in command line)

**Comment by DuVogel87** [comment]
Thanks. 

Do you happen to have any idea how I can integrate the metadata into Agisoft Metashape?

**Comment by AdrianEddy** [comment]
I have no idea, never heard of this software
