### ISSUE TITLE
Why Does gyro2bb Report "Unsupported File Format" for MP4 Files?

### ISSUE THREAD

**Issue by DuVogel87** [AdrianEddy/telemetry-parser#40]
I am encountering an issue with gyro2bb. When I try to process an MP4 file that I converted from an Insta360 .insv file using Insta360 Studio, the following error is displayed:

`thread 'main' panicked at gyro2bb.rs:38:113:
called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "Unsupported file format" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
`
I used Insta360 Studio to export the file with stabilization turned off, and I selected the MP4 format. Since MP4 is listed as a supported format, I’m unsure why this error occurs.

Could you clarify if there are specific requirements for MP4 files to be processed (e.g., encoding format, metadata retention)? Or does this tool require the native .insv file instead?

Thank you for your help!

**Comment by AdrianEddy** [comment]
The metadata is not preserved when converting. You have to use the original insv file

**Comment by mthaddon** [comment]
Hope it's okay to add a comment to a closed issue. Do you know if the file format has changed with the Insta360 Ace Pro 2? If I look on the SD card, all I see is a ".mp4" and a ".lrv" file, both of which return `"Unsupported file format"` from `./gyro2bb --dump ${FILENAME}`.

**Comment by DuVogel87** [comment]
@mthaddon I dont know the Ace Pro series and have no experience with it.
