### ISSUE TITLE
Work flow

### ISSUE THREAD

**Issue by hi6otb** [AdrianEddy/telemetry-parser#5]
1. Recording video "Stab off" on Sony camera.
2. gyro2bb C0101.mp4
3. I can get C0101.MP4.csv (it's gyro and accel data)
4. open gyroflow-dev
5. Setting "Input parameter" as attempted phot
<img width="256" alt="input" src="https://user-images.githubusercontent.com/46843043/149599782-9d22ba9a-2d0b-46bd-9952-d575c604d351.PNG">
6. Attempt auto sync (but it say error "No valid syncpoints")

Please check my file.
I use ZV-E10 and SEL1018 10mm
https://drive.google.com/drive/folders/1U0CwTKSniVu5ERf1gIbDmlAl8IfeVXai?usp=sharing

**Comment by AdrianEddy** [comment]
Use new Gyroflow: https://github.com/gyroflow/gyroflow/releases
